name: Publish to PyPI

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  release:
    types: [published]  # Trigger on published GitHub releases

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Adjust for your Python version compatibility

      - name: Install dependencies
        run: |
          pip install build twine

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
