AVAILABLE_API_MODELS = ['gpt-3.5-turbo', 'gpt-4'] 

PROB_AVAILABLE_API_MODELS = ['gpt-3.5-turbo']

ACTIVATION_AVAILABLE_API_MODELS = []

AVAILABLE_DATASETS = ['trivia_qa']

AVAILABLE_EVALUATION_METRICS = ['auroc']